# This is a sample build configuration for all languages.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
# image: docker-image:tag
image: node:8.0.0

pipelines:
  install:
    - step:
        script:
          - npm install
          - npm test
  test:
    - step:
        script:
          - npm install
          - npm test
  lint:
    - step:
        script:
          - npm install
          - npm lint
