import ReduxUtils from 'core/utils/ReduxUtils'

export default {
  ResourceNames: {
    Language: 'TextComponentLanguage',
    Value: 'TextComponentValue',
    Text: 'TextComponent'
  },
  SET_INIT_LANGUAGE: ReduxUtils.createAsyncResponseActionNames('SET_INIT_LANGUAGE'),
  'SET_LANGUAGE': 'SET_LANGUAGE',
  'SET_LANGUAGES': 'SET_LANGUAGEs',
  'UPDATE_MESSAGES': 'UPDATE_MESSAGES',
  LOAD_LANGUAGE_FILES: ReduxUtils.createAsyncResponseActionNames('LOAD_LANGUAGE_FILES'),
  'SET_LANGUAGE_REQUEST': 'SET_LANGUAGE_REQUEST',
  'SET_LANGUAGE_SUCCESS': 'SET_LANGUAGE_SUCCESS',
  'SET_LANGUAGE_FAILURE': 'SET_LANGUAGE_FAILURE',
  'INTL_KEY_NEW': 'INTL_KEY_NEW',
  'STORAGE_KEY': 'language',
  'INTL_KEY_VISIBLE': 'INTL_KEY_VISIBLE',
  'INTL_KEY_HIDE': 'INTL_KEY_HIDE',
  'REMOVE_KEY': 'REMOVE_KEY',
  'INTL_KEY_EDIT_SWITCH': 'INTL_KEY_EDIT_SWITCH',
  'INTL_KEY_EDIT_START': 'INTL_KEY_EDIT_START',
  'INTL_KEY_EDIT_END': 'INTL_KEY_EDIT_END',
  'INTL_KEY_DELETE_VALUE': 'INTL_KEY_DELETE_VALUE',
  'INTL_EDITOR_TOGGLE': 'INTL_EDITOR_TOGGLE'
}
